### ISSUE TITLE
Feature: Support for guzzle 7

### ISSUE THREAD

**Issue by timkung** [silverstripe-terraformers/silverstripe-swiftype#29]
Hello!

Just wondering if it would be easy to add support for guzzle 7?

A few other common silverstripe modules require guzzle 7 so it would allow us to pull in the latest version of this :)

Thanks!

**Comment by chrispenny** [comment]
Thanks, @timkung. If you're able to please raise a PR with any upgrade requirements, I'll be happy to review it.

Not sure what might be relevant for us.
https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

**Comment by chrispenny** [comment]
Closing as the current version now uses Guzzle 7.
