### ISSUE TITLE
Update README - Remove Warning

### ISSUE THREAD

**Issue by phptek** [silverstripe-terraformers/silverstripe-swiftype#34]
I'm super keen to use this module in an upcoming project but the warning in the README is _very_ offputting and even more so I'd imagine for more junior developers. How valid is the warning nowadays? How stable is the module? Please consider updating the README to remove or further qualify the warning.

Thanks!

**Comment by chrispenny** [comment]
Thanks for bringing that up, @phptek. We just haven't paid enough attention to the README.

The warning has been removed; the module has been considered stable since July 2020. New tags have been made for `1.1.1` and `2.0.1`.

**Comment by phptek** [comment]
> Thanks for bringing that up, @phptek. We just haven't paid enough attention to the README.
> 
> The warning has been removed; the module has been considered stable since July 2020. New tags have been made for `1.1.1` and `2.0.1`.

Oh you absolute legend. Thank you :-)
